%% Figure_plots.m
% Authors: Zyaire Howard and Jake Colwell
% Created: ???
% Last Major Modification: April 17, 2025
% Script to loop through all of the data generated by a study and create 
% the plots that are necessary for tuning stopping criteria, comparing models, etc.

%% Trial Surfaces Plot
close all; clear; clc;
addpath(genpath(fullfile(pwd)))
surfs = {@Surface1a,@Surface1b,@Surface1c,@Surface2a,@Surface2b,@Surface2c,@Surface3a,@Surface3b,@Surface3c};

Inputs

x=linspace(x_min+pad, x_max-pad, res_s);
y=linspace(y_min+pad, y_max-pad, res_s);
[x, y]=meshgrid(x,y);
x=x(:);y=y(:);

f = figure('Position',[0 0 600 460]);
title('Trial Surfaces')
tiledlayout(f,'flow','TileSpacing','tight','Padding','loose')
for i=[7 8 9 4 5 6 1 2 3]
    nexttile
    dasurf=surfs{i};
    z=dasurf(x,y);
    surf(reshape(x,res_s,res_s),reshape(y,res_s,res_s),reshape(z,res_s,res_s),'LineStyle','none')
    title(func2str(dasurf))
    view(3)
    xlabel('x (mm)')
    ylabel('y (mm)')
    zlabel('z (mm)')
    axis equal
    axis off
    grid off
end
annotation('arrow',[0.15 .85],[.1 .1])
annotation('arrow',[.1 .1],[0.15 .85])
annotation('textbox',[0.4 0 .2 .1],'String','Deviation','LineStyle','none','HorizontalAlignment','center','VerticalAlignment','middle',...
    'FontSize',12,'FontWeight','bold')
annotation('textbox',[0.1 0.4 .2 .1],'String','Complexity','LineStyle','none','HorizontalAlignment','center','VerticalAlignment','middle',...
    'Rotation',90,'FontSize',12,'FontWeight','bold')
fontsize(scale=1.5)

savefig('Paper Figures/3 Surfaces/TrialSurface.fig')
exportgraphics(f,'Paper Figures/3 Surfaces/TrialSurface.png')
exportgraphics(f,'Paper Figures/3 Surfaces/TrialSurface.eps')