%% Figure_plots.m
% Authors: Zyaire Howard and Jake Colwell
% Created: ???
% Last Major Modification: December 3, 2025
% Script to loop through all of the data generated by a study and create 
% the plots that are necessary for tuning stopping criteria, comparing models, etc.

%% Trial Surfaces Plot
close all; clear; clc;
addpath(genpath(fullfile(pwd)))
surfs = {@Surface1a,@Surface1b,@Surface1c,@Surface2a,@Surface2b,@Surface2c,@Surface3a,@Surface3b,@Surface3c};

Inputs

x=linspace(x_min+pad, x_max-pad, res_s);
y=linspace(y_min+pad, y_max-pad, res_s);
[x, y]=meshgrid(x,y);
x=x(:);y=y(:);

f = figure('Position',[0 0 600 460]);
%title('Trial Surfaces')
tiledlayout(f,'flow','TileSpacing','tight','Padding','loose')
for i=[7 8 9 4 5 6 1 2 3]
    nexttile
    dasurf=surfs{i};
    z=dasurf(x,y);
    surf(reshape(x,res_s,res_s),reshape(y,res_s,res_s),reshape(z,res_s,res_s),'LineStyle','none')
    %title(func2str(dasurf))
    view(3)
    xlabel('x (mm)')
    ylabel('y (mm)')
    zlabel('z (mm)')
    axis equal
    axis off
    grid off
end
colormap('viridis')
annotation('arrow',[0.15 .9],[.1 .1])
annotation('arrow',[.1 .1],[0.15 .9])
annotation('textbox',[0.4 0 .2 .05],'String','Deviation','LineStyle','none','HorizontalAlignment','center','VerticalAlignment','bottom',...
    'FontSize',12,'FontWeight','bold','Margin',0,'FitBoxToText','off')
annotation('textbox',[0.04 0.4 .2 .05],'String','Complexity','LineStyle','none','HorizontalAlignment','center','VerticalAlignment','top',...
    'Rotation',90,'FontSize',12,'FontWeight','bold','Margin',0)

annotation('line',[7 7]/30,[.11 .09])
annotation('line',[15 15]/30,[.11 .09])
annotation('line',[23 23]/30,[.11 .09])
annotation('textbox',[7/30-.05 .06-.05 .1 .1],'String','A','LineStyle','none','HorizontalAlignment','center','VerticalAlignment','middle','FontSize',12,'Margin',0)
annotation('textbox',[15/30-.05 .06-.05 .1 .1],'String','B','LineStyle','none','HorizontalAlignment','center','VerticalAlignment','middle','FontSize',12,'Margin',0)
annotation('textbox',[23/30-.05 .06-.05 .1 .1],'String','C','LineStyle','none','HorizontalAlignment','center','VerticalAlignment','middle','FontSize',12,'Margin',0)

annotation('line',[.11 .09],[7 7]/30)
annotation('line',[.11 .09],[15 15]/30)
annotation('line',[.11 .09],[23 23]/30)
annotation('textbox',[.07-.05 7/30-.05 .1 .1],'String','1','LineStyle','none','HorizontalAlignment','center','VerticalAlignment','middle','FontSize',12,'Margin',0)
annotation('textbox',[.07-.05 15/30-.05 .1 .1],'String','2','LineStyle','none','HorizontalAlignment','center','VerticalAlignment','middle','FontSize',12,'Margin',0)
annotation('textbox',[.07-.05 23/30-.05 .1 .1],'String','3','LineStyle','none','HorizontalAlignment','center','VerticalAlignment','middle','FontSize',12,'Margin',0)

fontsize(scale=1.5)

savefig('Paper Figures/3 Surfaces/TrialSurface.fig')
exportgraphics(f,'Paper Figures/3 Surfaces/TrialSurface.png')
exportgraphics(f,'Paper Figures/3 Surfaces/TrialSurface.eps')