%% Figure_plots.m
% Authors: Zyaire Howard and Jake Colwell
% Created: ???
% Last Major Modification: April 17, 2025
% Script to loop through all of the data generated by a study and create 
% the plots that are necessary for tuning stopping criteria, comparing models, etc.

%% Appendix Plot
% Check if the NURBS toolbox is available
% if exist('nrbmak', 'file') ~= 2
%     error('NURBS toolbox not found. Download and install the NURBS toolbox for MATLAB.');
% end
% 
% % Number of control points per curve
% numPoints = 10;
% 
% % Number of curve sets (each set has an upper, middle, and lower curve)
% numCurves = 9;
% 
% % Define X offsets for each curve set to space them out
% xOffsets = linspace(-20, 20, numCurves); % Evenly distribute along X-axis
% 
% % Shift all curves up so the lowest curve ends at (y=10, z=0)
% zShift = 8;  % Shift amount to move all curves up
% 
% % Define relative downward shifts for the middle and lower curves
% zOffsetLower = -4 + zShift;   % Moves middle curves downward
% zOffsetBottom = -8 + zShift;  % Moves bottom curves further downward
% zOffsetUpper = 0 + zShift;    % Moves upper curves up
% 
% % Create figure
% figure(1);
% set(gcf, 'Name', 'Error Metrics Plot', 'WindowStyle', 'docked');
% hold on;
% 
% % Loop through and generate each set of curves (upper, middle, bottom)
% for i = 1:numCurves
%     % Define Y values (evenly spaced from 0 to 10)
%     y = linspace(0, 10, numPoints)';
% 
%     % Define base Z values for the upper curves
%     z_upper = -y + 10 + zOffsetUpper;  % Shifted upper curves up
%     z_lower = -y + 10 + zOffsetLower;  % Shifted middle curves
%     z_bottom = -y + 10 + zOffsetBottom; % Shifted bottom curves
% 
%     % Randomly vary middle 8 Z values for all curves
%     z_upper(2:end-1) = z_upper(2:end-1) + (rand(numPoints-2, 1) - 0.5) * 4; 
%     z_lower(2:end-1) = z_lower(2:end-1) + (rand(numPoints-2, 1) - 0.5) * 4;
%     z_bottom(2:end-1) = z_bottom(2:end-1) + (rand(numPoints-2, 1) - 0.5) * 4;
% 
%     % Define X values with offset
%     x = ones(size(y)) * xOffsets(i);
% 
%     % Create and plot upper, middle, and bottom curves
%     for j = 1:3
%         if j == 1
%             z = z_upper; % Upper curve
%             color = 'r'; % Red color
%             lineStyle = '-'; % Solid line
%         elseif j == 2
%             z = z_lower; % Middle curve
%             color = 'b'; % Blue color
%             lineStyle = '--'; % Dashed line
%         else
%             z = z_bottom; % Bottom curve
%             color = 'k'; % Black color
%             lineStyle = ':'; % Dotted line
%         end
% 
%         % Combine into control points matrix
%         controlPoints = [x'; y'; z'];
% 
%         % Define a uniform knot vector for a cubic NURBS curve (degree 3)
%         degree = 3;
%         knotVector = [zeros(1, degree+1), linspace(0, 1, numPoints-degree), ones(1, degree+1)];
% 
%         % Define uniform weights (NURBS becomes B-spline when all weights are 1)
%         weights = ones(1, numPoints);
% 
%         % Create the NURBS curve
%         nurbsCurve = nrbmak([controlPoints; weights], knotVector);
% 
%         % Evaluate the NURBS curve
%         numEvalPoints = 100;  % Number of points to evaluate the curve
%         evalParams = linspace(0, 1, numEvalPoints);  
%         curvePoints = nrbeval(nurbsCurve, evalParams);
% 
%         % Plot the NURBS curve
%         plot3(curvePoints(1, :), curvePoints(2, :), curvePoints(3, :), ...
%             'Color', color, 'LineStyle', lineStyle, 'LineWidth', 2);
%     end
% end
% 
% % Set axis labels and title
% xlabel('Surface (X-axis)');
% ylabel('n [number of points] (Y-axis)');
% zlabel('Error Metric [mm] (Z-axis)');
% title('Method used');
% 
% % Flip the Y-axis in the plot
% set(gca, 'YDir', 'reverse');
% 
% % Add legend
% leg = legend({'Test', 'Train', 'CV'}, 'Location', 'northwest');
% 
% % Get current position of the legend
% legendPos = leg.Position;  
% 
% % Move the legend down by 100 pixels (Y direction)
% legendPos(2) = legendPos(2) - 0.2;  % Adjust this value as needed
% 
% % Apply new position to the legend
% leg.Position = legendPos;
% % Set custom X, Y, and Z limits
% xlim([-20, 20]);
% ylim([0, 10]);
% zlim([-5, 20]);
% 
% % Label X-axis with custom tick labels
% xticks(xOffsets);
% xticklabels({'1a', '1b', '1c', '2a', '2b', '2c', '3a', '3b', '3c'});
% 
% % Set aspect ratio
% pbaspect([3 1 1]);
% 
% % Set view for better visualization
% view(3);
% 
% % Grid for clarity
% grid on;
% ax = gca;
% ax.FontSize = 12;
% % Set view for better visualization
% view(3);  % Change if needed (e.g., view([angleX, angleY]))
% 
% % Grid for clarity
% grid on;
% ax = gca;
% ax.FontSize = 16;

%% Acquisition Function Figure (6 plots)
% Average over the same surface complexity (over 1a, 1b, 1c)
close all; clear; clc;

% Load data
addpath(genpath(fullfile(pwd)))
basepath = "Data/Results/20250411_SimStudy2/";
dirnames = dir(basepath+"*sim*");

LD_Surf1 = [];
LCB_Surf1 = [];
IVR2_Surf1 = [];

LD_Surf2 = [];
LCB_Surf2 = [];
IVR2_Surf2 = [];

LD_Surf3 = [];
LCB_Surf3 = [];
IVR2_Surf3 = [];

% for i = 1:size(dirnames,1)
for i = 1:21
    % Load data
    dirname = basepath + "/" + dirnames(i).name;
    fname = dirname + "/" + dirnames(i).name + ".mat";
    load(fname, 'modelPerformance'); % ME is 0 over all simulation runs
    load(fname, 'n');
    load(fname, 'nameB');
    load(fname, 'method');
    if method ~= 1
        load(fname, 'A');
    
        % Remove number of initial points
        modelPerformance(1:n - 1, :) = [];
    
        % Remove number of initial points
        InitialSamplingPoints = n - 1;
        modelPerformance(1:InitialSamplingPoints, :) = [];
        SimulationIteration = size(modelPerformance, 1);
    
        % Error Metrics 
        % Root Mean Squared Error
        RMSE_test = table2array(modelPerformance.Test(:, 4));
        RMSE_train = table2array(modelPerformance.Train(:, 4));
        RMSE_CV = table2array(modelPerformance.CV(:, 4));
    
        AcquisitionFunction = func2str(A);
        % Plot Calculation
        if isequal(AcquisitionFunction,'LD') &&...
          (isequal(nameB, 'Surf1a') || isequal(nameB, 'Surf1b') || isequal(nameB, 'Surf1c'))
            LD_Surf1 = cat(2, LD_Surf1, RMSE_train);
        elseif isequal(AcquisitionFunction,'LD') &&...
          (isequal(nameB, 'Surf2a') || isequal(nameB, 'Surf2b') || isequal(nameB, 'Surf2c'))
            LD_Surf2 = cat(2, LD_Surf2, RMSE_train);
        elseif isequal(AcquisitionFunction,'LD') &&...
          (isequal(nameB, 'Surf3a') || isequal(nameB, 'Surf3b') || isequal(nameB, 'Surf3c'))
            LD_Surf3 = cat(2, LD_Surf3, RMSE_train);

        elseif isequal(AcquisitionFunction,'LCB_exp') &&...
          (isequal(nameB, 'Surf1a') || isequal(nameB, 'Surf1b') || isequal(nameB, 'Surf1c'))
            LCB_Surf1 = cat(2, LCB_Surf1, RMSE_train);
        elseif isequal(AcquisitionFunction,'LCB_exp') &&...
          (isequal(nameB, 'Surf2a') || isequal(nameB, 'Surf2b') || isequal(nameB, 'Surf2c'))
            LCB_Surf2 = cat(2, LCB_Surf2, RMSE_train);
        elseif isequal(AcquisitionFunction,'LCB_exp') &&...
          (isequal(nameB, 'Surf3a') || isequal(nameB, 'Surf3b') || isequal(nameB, 'Surf3c'))
            LCB_Surf3 = cat(2, LCB_Surf3, RMSE_train);

        elseif isequal(AcquisitionFunction,'IVR2') &&...
          (isequal(nameB, 'Surf1a') || isequal(nameB, 'Surf1b') || isequal(nameB, 'Surf1c'))
            IVR2_Surf1 = cat(2, IVR2_Surf1, RMSE_train);
        elseif isequal(AcquisitionFunction,'IVR2') &&...
          (isequal(nameB, 'Surf2a') || isequal(nameB, 'Surf2b') || isequal(nameB, 'Surf2c'))
            IVR2_Surf2 = cat(2, IVR2_Surf2, RMSE_train);
        elseif isequal(AcquisitionFunction,'IVR2') &&...
          (isequal(nameB, 'Surf3a') || isequal(nameB, 'Surf3b') || isequal(nameB, 'Surf3c'))
            IVR2_Surf3 = cat(2, IVR2_Surf3, RMSE_train);
        end
    end
end



% % Number of iterations from simulation run
% iteration = linspace(n,...
%                      size(modelPerformance, 1) + InitialSamplingPoints,...
%                      size(modelPerformance, 1))';
% DeviationIteration = iteration;
% DeviationIteration(1) = [];
% 
% % Plot all curves in Figure 2 (docked)
% figure(1);
% set(gcf, 'Name', 'Acquesition Function Plot','WindowStyle', 'docked');
% plot(DeviationIteration, yy1 +20, 'b-', 'LineWidth', 2); hold on;
% plot(DeviationIteration, yy2 +20, 'r-', 'LineWidth', 2);
% plot(DeviationIteration, yy3 +20, 'k-', 'LineWidth', 2);
% 
% % standrnd deviation for error bars
% % errorbar(x, y1 +20, err, 'bo', 'MarkerFaceColor', 'b');
% % errorbar(x, y2 +20, err, 'ro', 'MarkerFaceColor', 'r');
% % errorbar(x, y3 +20, err, 'ko', 'MarkerFaceColor', 'k');
% xlim([n, inf]);
% legend('acquisition function 1', 'acquisition function 2', 'acquisition function 3', ...
%        'NumColumns',3,'Location','southoutside');
% xlabel('n [number of points]');
% ylabel('RMSE [mm]');
% title('Acquisition Functions Averaged Across Suface Diveation');
% fontsize(gcf, scale=1.5)
% grid on

%% Full Stopping Criteria Figures
clc; clear; close all;

% Load data
addpath(genpath(fullfile(pwd)))
basepath = "Data/Results/20250417_SimStudy3/";
dirnames = dir(basepath+"*sim*");

for i = 1:size(dirnames,1)
    % Load data
    dirname = basepath + dirnames(i).name;
    fname = dirname + "/" + dirnames(i).name + ".mat";
    load(fname, 'modelPerformance'); % ME is 0 over all simulation runs
    load(fname, 'n');
    load(fname, 'SurfB');
    load(fname, 'method');

    % Error Metrics
    
    % Critical Numbers
    criticalNumber1 = 0.165;
    criticalNumber2 = 0.5;
    criticalNumber3 = 6e-4;
    criticalNumber4 = 0.1;

    % Ideal:
    % Guarantee of Point Quality
    [IdealGuarantee, printNumberIG] = Guarantee(modelPerformance,'Ideal',criticalNumber1);
    % Confidence Testing
    [IdealConfidenceTesting, printNumberICT] = ConfidenceTesting(modelPerformance,'Ideal',criticalNumber2);
    % Error Convergence
    [IdealErrorConvergence, printNumberIEC] = ErrorConvergence(modelPerformance,'Ideal',criticalNumber3);
    % Error Agreement    
    [IdealErrorAgreement, printNumberIEA] = ErrorAgreement(modelPerformance,'Ideal',criticalNumber4);

    % Actual:
    % Guarantee of Point Quality
    [ActualGuarantee, printNumberAG] = Guarantee(modelPerformance,'Actual',criticalNumber1);
    % Confidence Testing
    [ActualConfidenceTesting, printNumberACT] = ConfidenceTesting(modelPerformance,'Actual',criticalNumber2);
    % Error Convergence
    [ActualErrorConvergence, printNumberAEC] = ErrorConvergence(modelPerformance,'Actual',criticalNumber3);
    % Error Agreement    
    [ActualErrorAgreement, printNumberAEA] = ErrorAgreement(modelPerformance,'Actual',criticalNumber4);

    % V2
    % Guarantee of Point Quality
    [V2Guarantee, printNumberVG] = Guarantee(modelPerformance,'V2',criticalNumber1);
    % Confidence Testing
    [V2ConfidenceTesting, printNumberVCT] = ConfidenceTesting(modelPerformance,'V2',criticalNumber2);
    % Error Convergence
    [V2ErrorConvergence, printNumberVEC] = ErrorConvergence(modelPerformance,'V2',criticalNumber3);
    
    % Plotting
    % Number of iterations from simulation run
    iteration = modelPerformance.n;
    DeviationIteration = iteration;
    DeviationIteration(1) = [];
 
    close(figure(3))
    figure(3)
    set(gcf,"Name",'All Stopping Criteria','WindowStyle','normal','Position',[0 0 1800 800])
    % Plotting Ideal Guarantee
    subplot(3,4,1)
    StoppingCriteriaPlots(iteration, IdealGuarantee, printNumberIG, criticalNumber1)
    title('Ideal Guarantee of Safety')
    
    % Plotting Ideal Confidence Testing
    subplot(3,4,2)
    StoppingCriteriaPlots(iteration, IdealConfidenceTesting, printNumberICT, criticalNumber2)
    title('Ideal Confidence Testing')
    
    % Plotting Ideal Error Convergence
    subplot(3,4,3)
    StoppingCriteriaPlots(DeviationIteration, IdealErrorConvergence, printNumberIEC, criticalNumber3)
    title('Ideal Error Convergence')
    
    % Plotting Ideal Error Agreement
    subplot(3,4,4)
    StoppingCriteriaPlots(iteration, IdealErrorAgreement, printNumberIEA, criticalNumber4)
    title('Ideal Error Agreement')

    % Plotting Actual Guarantee
    subplot(3,4,5)
    StoppingCriteriaPlots(iteration, ActualGuarantee, printNumberAG, criticalNumber1)
    title('Actual Guarantee of Safety')
    
    % Plotting Actual Confidence Testing
    subplot(3,4,6)
    StoppingCriteriaPlots(iteration, ActualConfidenceTesting, printNumberACT, criticalNumber2)
    title('Actual Confidence Testing')

    % Plotting Actual Error Convergence
    subplot(3,4,7)
    StoppingCriteriaPlots(DeviationIteration, ActualErrorConvergence, printNumberAEC, criticalNumber3)
    title('Actual Error Convergence')
    
    % Plotting Actual Error Agreement
    subplot(3,4,8)
    StoppingCriteriaPlots(iteration, ActualErrorAgreement, printNumberAEA, criticalNumber4)
    title('Actual Error Agreement')

    % Plotting V2 Guarantee
    subplot(3,4,9)
    StoppingCriteriaPlots(iteration, V2Guarantee, printNumberVG, criticalNumber1)
    title('V2 Guarantee of Safety')

    % Plotting V2 Confidence Testing
    subplot(3,4,10)
    StoppingCriteriaPlots(iteration, V2ConfidenceTesting, printNumberVCT, criticalNumber2)
    title('V2 Confidence Testing')

    % Plotting V2 Error Convergence
    subplot(3,4,11)
    StoppingCriteriaPlots(DeviationIteration, V2ErrorConvergence, printNumberVEC, criticalNumber3)
    title('V2 Error Convergence')

    fontsize(gcf, scale=1.5)
    saveas(figure(3),dirname + "/" + dirnames(i).name + "_ferr" + ".fig")
    saveas(figure(3),dirname + "/" + dirnames(i).name + "_ferr" + ".png")
    saveas(figure(3),dirname + "/" + dirnames(i).name + "_ferr" + ".eps")
end

%% Stopping Criteria Summary Figure
clc; clear; close all;

% Load data
addpath(genpath(fullfile(pwd)))
basepath = "Data/Results/20250417_SimStudy3/";
dirnames = dir(basepath+"*sim*");

figure(10);
set(gcf, 'Name', 'Criteria Tuning Helper','WindowStyle', 'normal','Position',[0 0 1280 840],'Color','white');
tl=tiledlayout(3,3);
ylabel(tl,'Stopping Criteria');
xlabel(tl,'Number of Points, n');
title(tl,'Stopping Criteria Comparison');
for i=1:9
    nexttile
    hold on
    yticks([0 1 2 4 5 6 8 9 10])
    yticklabels(["G","CT","EC","G","CT","EC","G","CT","EC"])
    set(gca,'YGrid','on')
    axis([-inf inf -1 11])
end

for i = 1:size(dirnames,1)
    % Load data
    dirname = basepath + dirnames(i).name;
    fname = dirname + "/" + dirnames(i).name + ".mat";
    load(fname, 'modelPerformance'); % ME is 0 over all simulation runs
    load(fname, 'n');
    load(fname, 'SurfB');
    load(fname, 'method');

    % Error Metrics
    
    % Critical Numbers
    criticalNumber1 = 0.165;
    criticalNumber2 = 0.5;
    criticalNumber3 = 6e-4;
    criticalNumber4 = 0.1;

    % Ideal:
    % Guarantee of Point Quality
    [IdealGuarantee, printNumberIG] = Guarantee(modelPerformance,'Ideal',criticalNumber1);
    % Confidence Testing
    [IdealConfidenceTesting, printNumberICT] = ConfidenceTesting(modelPerformance,'Ideal',criticalNumber2);
    % Error Convergence
    [IdealErrorConvergence, printNumberIEC] = ErrorConvergence(modelPerformance,'Ideal',criticalNumber3);
    % Error Agreement    
    [IdealErrorAgreement, printNumberIEA] = ErrorAgreement(modelPerformance,'Ideal',criticalNumber4);

    % Actual:
    % Guarantee of Point Quality
    [ActualGuarantee, printNumberAG] = Guarantee(modelPerformance,'Actual',criticalNumber1);
    % Confidence Testing
    [ActualConfidenceTesting, printNumberACT] = ConfidenceTesting(modelPerformance,'Actual',criticalNumber2);
    % Error Convergence
    [ActualErrorConvergence, printNumberAEC] = ErrorConvergence(modelPerformance,'Actual',criticalNumber3);
    % Error Agreement    
    [ActualErrorAgreement, printNumberAEA] = ErrorAgreement(modelPerformance,'Actual',criticalNumber4);

    % V2
    % Guarantee of Point Quality
    [V2Guarantee, printNumberVG] = Guarantee(modelPerformance,'V2',criticalNumber1);
    % Confidence Testing
    [V2ConfidenceTesting, printNumberVCT] = ConfidenceTesting(modelPerformance,'V2',criticalNumber2);
    % Error Convergence
    [V2ErrorConvergence, printNumberVEC] = ErrorConvergence(modelPerformance,'V2',criticalNumber3);
    
    % Plotting
    % Number of iterations from simulation run
    iteration = modelPerformance.n;
    DeviationIteration = iteration;
    DeviationIteration(1) = [];

    figure(10)
    row = 4-str2double(SurfB(5));
    if SurfB(6)=='a'
        col=1;
    elseif SurfB(6)=='b'
        col=2;
    elseif SurfB(6)=='c'
        col=3;
    end
    subplotnum = 3*(row-1)+col;
    nexttile(subplotnum)
    title(SurfB(1:6))
    ys = [0 1 2]+4*(method-1);
    msize=100;
    scatter([printNumberIG printNumberICT printNumberIEC],ys,msize,[0.8500 0.3250 0.0980],'filled','o','MarkerFaceAlpha',0.2)
    scatter([printNumberIG printNumberICT printNumberIEC],ys,msize,[0.8500 0.3250 0.0980],'o','LineWidth',1)
    scatter([printNumberIG printNumberICT printNumberIEC],ys,5,[0.8500 0.3250 0.0980],'.')
    scatter([printNumberAG printNumberACT printNumberAEC],ys,msize,[0.9290 0.6940 0.1250],'filled','^','MarkerFaceAlpha',0.2)
    scatter([printNumberAG printNumberACT printNumberAEC],ys,msize,[0.9290 0.6940 0.1250],'^','LineWidth',1)
    scatter([printNumberAG printNumberACT printNumberAEC],ys,5,[0.9290 0.6940 0.1250],'.')
    scatter([printNumberVG printNumberVCT printNumberVEC],ys,msize,[0.4940 0.1840 0.5560],'filled','square','MarkerFaceAlpha',0.2)
    scatter([printNumberVG printNumberVCT printNumberVEC],ys,msize,[0.4940 0.1840 0.5560],'square','LineWidth',1)
    scatter([printNumberVG printNumberVCT printNumberVEC],ys,5,[0.4940 0.1840 0.5560],'.')
end
fig = gcf;
Lgnd = legend('','Ideal','','','Actual','','','V2','Orientation','horizontal');
Lgnd.Location = 'Layout';
Lgnd.Layout.Tile = 'South';
fontsize('scale',1.5)

saveas(figure(10),strcat(basepath,'StoppingCriteriaComp.fig'))
exportgraphics(figure(10),strcat(basepath,'StoppingCriteriaComp.png'))
exportgraphics(figure(10),strcat(basepath,'StoppingCriteriaComp.eps'))

%% Method Comparison Figure
clc; clear; close all;

% Load data
addpath(genpath(fullfile(pwd)))
basepath = "Data/Results/20250417_SimStudy3/";
dirnames = dir(basepath+"*sim*");

figure(10);
set(gcf, 'Name', 'Method Comparison','WindowStyle', 'normal','Position',[0 0 640 420],'Color','white');
hold on
yticks([0 1 2 4 5 6 8 9 10 11])
yticklabels(["1A","1B","1C","2A","2B","2C","3A","3B","3C",''])
xticks([0 25 50 75 100 125 150])
%set(gca,'YGrid','on')
grid on
axis([0 150 -1 11])
title('Convergence Speed Comparison')
xlabel('Number of Points, n')
ylabel('Surface')

for i = 1:size(dirnames,1)
    % Load data
    dirname = basepath + dirnames(i).name;
    fname = dirname + "/" + dirnames(i).name + ".mat";
    load(fname, 'modelPerformance','n','SurfB','method');

    % Error Metrics
    ns{i}=modelPerformance.n;
    [IdealGuarantee{i}, printNumberIGs{i}] = MiniCriteria(modelPerformance,0.165/4.5);
    printNumberIG=printNumberIGs{i};
    figure(10)
    row_maj = str2double(SurfB(5));
    if SurfB(6)=='a'
        row_min=0;
    elseif SurfB(6)=='b'
        row_min=1;
    elseif SurfB(6)=='c'
        row_min=2;
    end
    row = 4*(row_maj-1)+row_min;
    if method == 1 
    scatter(printNumberIG,row,150,[0.8500 0.3250 0.0980],'filled','o','MarkerFaceAlpha',0.2)
    scatter(printNumberIG,row,150,[0.8500 0.3250 0.0980],'o','LineWidth',1)
    elseif method == 2
    scatter(printNumberIG,row,200,[0.9290 0.6940 0.1250],'filled','^','LineWidth',2,'MarkerFaceAlpha',0.2,'MarkerEdgeAlpha',1)
    scatter(printNumberIG,row,150,[0.9290 0.6940 0.1250],'^','LineWidth',1)
    elseif method == 3
    scatter(printNumberIG,row,150,[0.4940 0.1840 0.5560],'filled','square','MarkerFaceAlpha',0.2,'MarkerEdgeAlpha',1)
    scatter(printNumberIG,row,150,[0.4940 0.1840 0.5560],'square','LineWidth',1)
    end
end
legend('','Method 1','','','','','','','','','','','','','','','','','','Method 2','','Method 3','Location','eastoutside')
fontsize('scale',1.5)

% saveas(figure(10),strcat(basepath,'ConvergenceSummary.fig'))
% exportgraphics(figure(10),strcat(basepath,'ConvergenceSummary.png'))
% exportgraphics(figure(10),strcat(basepath,'ConvergenceSummary.eps'))