%% Figure_plots.m
% Authors: Zyaire Howard and Jake Colwell
% Created: ???
% Last Major Modification: April 17, 2025
% Script to loop through all of the data generated by a study and create 
% the plots that are necessary for tuning stopping criteria, comparing models, etc.

%% Full Stopping Criteria Figures
clc; clear; close all;

% Load data
addpath(genpath(fullfile(pwd)))
basepath = "Data/Results/20250417_SimStudy3/";
dirnames = dir(basepath+"*sim*");

for i = 1:size(dirnames,1)
    % Load data
    dirname = basepath + dirnames(i).name;
    fname = dirname + "/" + dirnames(i).name + ".mat";
    load(fname, 'modelPerformance'); % ME is 0 over all simulation runs
    load(fname, 'n');
    load(fname, 'SurfB');
    load(fname, 'method');

    % Error Metrics
    
    % Critical Numbers
    criticalNumber1 = 0.165;
    criticalNumber2 = 0.5;
    criticalNumber3 = 6e-4;
    criticalNumber4 = 0.1;

    % Ideal:
    % Guarantee of Point Quality
    [IdealGuarantee, printNumberIG] = Guarantee(modelPerformance,'Ideal',criticalNumber1);
    % Confidence Testing
    [IdealConfidenceTesting, printNumberICT] = ConfidenceTesting(modelPerformance,'Ideal',criticalNumber2);
    % Error Convergence
    [IdealErrorConvergence, printNumberIEC] = ErrorConvergence(modelPerformance,'Ideal',criticalNumber3);
    % Error Agreement    
    [IdealErrorAgreement, printNumberIEA] = ErrorAgreement(modelPerformance,'Ideal',criticalNumber4);

    % Actual:
    % Guarantee of Point Quality
    [ActualGuarantee, printNumberAG] = Guarantee(modelPerformance,'Actual',criticalNumber1);
    % Confidence Testing
    [ActualConfidenceTesting, printNumberACT] = ConfidenceTesting(modelPerformance,'Actual',criticalNumber2);
    % Error Convergence
    [ActualErrorConvergence, printNumberAEC] = ErrorConvergence(modelPerformance,'Actual',criticalNumber3);
    % Error Agreement    
    [ActualErrorAgreement, printNumberAEA] = ErrorAgreement(modelPerformance,'Actual',criticalNumber4);

    % V2
    % Guarantee of Point Quality
    [V2Guarantee, printNumberVG] = Guarantee(modelPerformance,'V2',criticalNumber1);
    % Confidence Testing
    [V2ConfidenceTesting, printNumberVCT] = ConfidenceTesting(modelPerformance,'V2',criticalNumber2);
    % Error Convergence
    [V2ErrorConvergence, printNumberVEC] = ErrorConvergence(modelPerformance,'V2',criticalNumber3);
    
    % Plotting
    % Number of iterations from simulation run
    iteration = modelPerformance.n;
    DeviationIteration = iteration;
    DeviationIteration(1) = [];
 
    close(figure(3))
    figure(3)
    set(gcf,"Name",'All Stopping Criteria','WindowStyle','normal','Position',[0 0 1800 800])
    % Plotting Ideal Guarantee
    subplot(3,4,1)
    StoppingCriteriaPlots(iteration, IdealGuarantee, printNumberIG, criticalNumber1)
    title('Ideal Guarantee of Safety')
    
    % Plotting Ideal Confidence Testing
    subplot(3,4,2)
    StoppingCriteriaPlots(iteration, IdealConfidenceTesting, printNumberICT, criticalNumber2)
    title('Ideal Confidence Testing')
    
    % Plotting Ideal Error Convergence
    subplot(3,4,3)
    StoppingCriteriaPlots(DeviationIteration, IdealErrorConvergence, printNumberIEC, criticalNumber3)
    title('Ideal Error Convergence')
    
    % Plotting Ideal Error Agreement
    subplot(3,4,4)
    StoppingCriteriaPlots(iteration, IdealErrorAgreement, printNumberIEA, criticalNumber4)
    title('Ideal Error Agreement')

    % Plotting Actual Guarantee
    subplot(3,4,5)
    StoppingCriteriaPlots(iteration, ActualGuarantee, printNumberAG, criticalNumber1)
    title('Actual Guarantee of Safety')
    
    % Plotting Actual Confidence Testing
    subplot(3,4,6)
    StoppingCriteriaPlots(iteration, ActualConfidenceTesting, printNumberACT, criticalNumber2)
    title('Actual Confidence Testing')

    % Plotting Actual Error Convergence
    subplot(3,4,7)
    StoppingCriteriaPlots(DeviationIteration, ActualErrorConvergence, printNumberAEC, criticalNumber3)
    title('Actual Error Convergence')
    
    % Plotting Actual Error Agreement
    subplot(3,4,8)
    StoppingCriteriaPlots(iteration, ActualErrorAgreement, printNumberAEA, criticalNumber4)
    title('Actual Error Agreement')

    % Plotting V2 Guarantee
    subplot(3,4,9)
    StoppingCriteriaPlots(iteration, V2Guarantee, printNumberVG, criticalNumber1)
    title('V2 Guarantee of Safety')

    % Plotting V2 Confidence Testing
    subplot(3,4,10)
    StoppingCriteriaPlots(iteration, V2ConfidenceTesting, printNumberVCT, criticalNumber2)
    title('V2 Confidence Testing')

    % Plotting V2 Error Convergence
    subplot(3,4,11)
    StoppingCriteriaPlots(DeviationIteration, V2ErrorConvergence, printNumberVEC, criticalNumber3)
    title('V2 Error Convergence')

    fontsize(gcf, scale=1.5)
    saveas(figure(3),dirname + "/" + dirnames(i).name + "_ferr" + ".fig")
    saveas(figure(3),dirname + "/" + dirnames(i).name + "_ferr" + ".png")
    saveas(figure(3),dirname + "/" + dirnames(i).name + "_ferr" + ".eps")
end
