makeNetwork
options = trainingOptions("adam",...
    "InitialLearnRate",0.001,...
    "GradientDecayFactor",0.98,...
    "Metrics",@multiloss,...
    "MiniBatchSize",64,...
    "MaxEpochs",100,...
    "ExecutionEnvironment","parallel-auto");

trained_net = trainnet(data,net,loss,options);

predict(trained_net,data)