clear;clc;close all
tic
makeNetwork
load("Data/M4/surf_dataset.mat")
t_init = toc;
fprintf('Time to load dataset and create network: %.2f\n',t_init)
options = trainingOptions("adam",...
    "InitialLearnRate",0.001,...
    "LearnRateSchedule",'exponential',...
    'LearnRateDropFactoar',0.90,...
    "MiniBatchSize",64,...
    "MaxEpochs",50,...
    "ExecutionEnvironment","auto",...
    'Plots','training-progress');

[trained_net, data] = trainnet(images,targets,net,@multiloss,options);

t_train = toc;
fprintf('Time to train network: %.f\n',t_train)

save("Method4/trained_network.mat","trained_net","-v7.3")
