%% Figure_plots.m
% Authors: Zyaire Howard and Jake Colwell
% Created: ???
% Last Major Modification: April 17, 2025
% Script to loop through all of the data generated by a study and create 
% the plots that are necessary for tuning stopping criteria, comparing models, etc.

%% Appendix Plot
% Check if the NURBS toolbox is available
% if exist('nrbmak', 'file') ~= 2
%     error('NURBS toolbox not found. Download and install the NURBS toolbox for MATLAB.');
% end
% 
% % Number of control points per curve
% numPoints = 10;
% 
% % Number of curve sets (each set has an upper, middle, and lower curve)
% numCurves = 9;
% 
% % Define X offsets for each curve set to space them out
% xOffsets = linspace(-20, 20, numCurves); % Evenly distribute along X-axis
% 
% % Shift all curves up so the lowest curve ends at (y=10, z=0)
% zShift = 8;  % Shift amount to move all curves up
% 
% % Define relative downward shifts for the middle and lower curves
% zOffsetLower = -4 + zShift;   % Moves middle curves downward
% zOffsetBottom = -8 + zShift;  % Moves bottom curves further downward
% zOffsetUpper = 0 + zShift;    % Moves upper curves up
% 
% % Create figure
% figure(1);
% set(gcf, 'Name', 'Error Metrics Plot', 'WindowStyle', 'docked');
% hold on;
% 
% % Loop through and generate each set of curves (upper, middle, bottom)
% for i = 1:numCurves
%     % Define Y values (evenly spaced from 0 to 10)
%     y = linspace(0, 10, numPoints)';
% 
%     % Define base Z values for the upper curves
%     z_upper = -y + 10 + zOffsetUpper;  % Shifted upper curves up
%     z_lower = -y + 10 + zOffsetLower;  % Shifted middle curves
%     z_bottom = -y + 10 + zOffsetBottom; % Shifted bottom curves
% 
%     % Randomly vary middle 8 Z values for all curves
%     z_upper(2:end-1) = z_upper(2:end-1) + (rand(numPoints-2, 1) - 0.5) * 4; 
%     z_lower(2:end-1) = z_lower(2:end-1) + (rand(numPoints-2, 1) - 0.5) * 4;
%     z_bottom(2:end-1) = z_bottom(2:end-1) + (rand(numPoints-2, 1) - 0.5) * 4;
% 
%     % Define X values with offset
%     x = ones(size(y)) * xOffsets(i);
% 
%     % Create and plot upper, middle, and bottom curves
%     for j = 1:3
%         if j == 1
%             z = z_upper; % Upper curve
%             color = 'r'; % Red color
%             lineStyle = '-'; % Solid line
%         elseif j == 2
%             z = z_lower; % Middle curve
%             color = 'b'; % Blue color
%             lineStyle = '--'; % Dashed line
%         else
%             z = z_bottom; % Bottom curve
%             color = 'k'; % Black color
%             lineStyle = ':'; % Dotted line
%         end
% 
%         % Combine into control points matrix
%         controlPoints = [x'; y'; z'];
% 
%         % Define a uniform knot vector for a cubic NURBS curve (degree 3)
%         degree = 3;
%         knotVector = [zeros(1, degree+1), linspace(0, 1, numPoints-degree), ones(1, degree+1)];
% 
%         % Define uniform weights (NURBS becomes B-spline when all weights are 1)
%         weights = ones(1, numPoints);
% 
%         % Create the NURBS curve
%         nurbsCurve = nrbmak([controlPoints; weights], knotVector);
% 
%         % Evaluate the NURBS curve
%         numEvalPoints = 100;  % Number of points to evaluate the curve
%         evalParams = linspace(0, 1, numEvalPoints);  
%         curvePoints = nrbeval(nurbsCurve, evalParams);
% 
%         % Plot the NURBS curve
%         plot3(curvePoints(1, :), curvePoints(2, :), curvePoints(3, :), ...
%             'Color', color, 'LineStyle', lineStyle, 'LineWidth', 2);
%     end
% end
% 
% % Set axis labels and title
% xlabel('Surface (X-axis)');
% ylabel('n [number of points] (Y-axis)');
% zlabel('Error Metric [mm] (Z-axis)');
% title('Method used');
% 
% % Flip the Y-axis in the plot
% set(gca, 'YDir', 'reverse');
% 
% % Add legend
% leg = legend({'Test', 'Train', 'CV'}, 'Location', 'northwest');
% 
% % Get current position of the legend
% legendPos = leg.Position;  
% 
% % Move the legend down by 100 pixels (Y direction)
% legendPos(2) = legendPos(2) - 0.2;  % Adjust this value as needed
% 
% % Apply new position to the legend
% leg.Position = legendPos;
% % Set custom X, Y, and Z limits
% xlim([-20, 20]);
% ylim([0, 10]);
% zlim([-5, 20]);
% 
% % Label X-axis with custom tick labels
% xticks(xOffsets);
% xticklabels({'1a', '1b', '1c', '2a', '2b', '2c', '3a', '3b', '3c'});
% 
% % Set aspect ratio
% pbaspect([3 1 1]);
% 
% % Set view for better visualization
% view(3);
% 
% % Grid for clarity
% grid on;
% ax = gca;
% ax.FontSize = 12;
% % Set view for better visualization
% view(3);  % Change if needed (e.g., view([angleX, angleY]))
% 
% % Grid for clarity
% grid on;
% ax = gca;
% ax.FontSize = 16;

%% Acquisition Function Figure (6 plots)
% Average over the same surface complexity (over 1a, 1b, 1c)
close all; clear; clc;

% Load data
addpath(genpath(fullfile(pwd)))
basepath = "Data/Results/20250423_SimStudy4/";
dirnames = dir(basepath+"*sim*");

LD_Surf1 = [];
LCB_Surf1 = [];
IVR2_Surf1 = [];

LD_Surf2 = [];
LCB_Surf2 = [];
IVR2_Surf2 = [];

LD_Surf3 = [];
LCB_Surf3 = [];
IVR2_Surf3 = [];

for i = 1:size(dirnames,1)
    % Load data
    dirname = basepath + "/" + dirnames(i).name;
    fname = dirname + "/" + dirnames(i).name + ".mat";
    load(fname, 'modelPerformance'); % ME is 0 over all simulation runs
    load(fname, 'nameB');
    load(fname, 'method');
    if method ~= 1
        load(fname, 'A');
    
        % Error Metrics 
        % Root Mean Squared Error
        MAE_test = table2array(modelPerformance.Test(:, 3));
        % RMSE_train = table2array(modelPerformance.Train(:, 4));
        % RMSE_CV = table2array(modelPerformance.CV(:, 4));
        if contains(nameB,'Surf1')
            n1=modelPerformance.n;
        elseif contains(nameB,'Surf2')
            n2=modelPerformance.n;
        elseif contains(nameB,'Surf3')
            n3=modelPerformance.n;
        end

        AcquisitionFunction = func2str(A);
        % Plot Calculation
        if isequal(AcquisitionFunction,'LD') && contains(nameB,'Surf1')
            LD_Surf1 = cat(2, LD_Surf1, MAE_test);
        elseif isequal(AcquisitionFunction,'LD') && contains(nameB,'Surf2')
            LD_Surf2 = cat(2, LD_Surf2, MAE_test);
        elseif isequal(AcquisitionFunction,'LD') && contains(nameB,'Surf3')
            LD_Surf3 = cat(2, LD_Surf3, MAE_test);

        elseif isequal(AcquisitionFunction,'LCB_exp') && contains(nameB,'Surf1')
            LCB_Surf1 = cat(2, LCB_Surf1, MAE_test);
        elseif isequal(AcquisitionFunction,'LCB_exp') && contains(nameB,'Surf2')
            LCB_Surf2 = cat(2, LCB_Surf2, MAE_test);
        elseif isequal(AcquisitionFunction,'LCB_exp') && contains(nameB,'Surf3')
            LCB_Surf3 = cat(2, LCB_Surf3, MAE_test);

        elseif isequal(AcquisitionFunction,'IVR2') && contains(nameB,'Surf1')
            IVR2_Surf1 = cat(2, IVR2_Surf1, MAE_test);
        elseif isequal(AcquisitionFunction,'IVR2') && contains(nameB,'Surf2')
            IVR2_Surf2 = cat(2, IVR2_Surf2, MAE_test);
        elseif isequal(AcquisitionFunction,'IVR2') && contains(nameB,'Surf3')
            IVR2_Surf3 = cat(2, IVR2_Surf3, MAE_test);
        end
    end
end

%% Calculate Means and Std Deviations
 close all;
IVR2_Surf1_m=mean(IVR2_Surf1,2);
IVR2_Surf2_m=mean(IVR2_Surf2,2);
IVR2_Surf3_m=mean(IVR2_Surf3,2);

LCB_Surf1_m=mean(LCB_Surf1,2);
LCB_Surf2_m=mean(LCB_Surf2,2);
LCB_Surf3_m=mean(LCB_Surf3,2);

LD_Surf1_m=mean(LD_Surf1,2);
LD_Surf2_m=mean(LD_Surf2,2);
LD_Surf3_m=mean(LD_Surf3,2);

IVR2_Surf1_std=std(IVR2_Surf1,0,2);
IVR2_Surf2_std=std(IVR2_Surf2,0,2);
IVR2_Surf3_std=std(IVR2_Surf3,0,2);

LCB_Surf1_std=std(LCB_Surf1,0,2);
LCB_Surf2_std=std(LCB_Surf2,0,2);
LCB_Surf3_std=std(LCB_Surf3,0,2);

LD_Surf1_std=std(LD_Surf1,0,2);
LD_Surf2_std=std(LD_Surf2,0,2);
LD_Surf3_std=std(LD_Surf3,0,2);

% Plot all curves in Figure 2 (docked)
figure('Position',[0 0 600 1000]);
set(gcf, 'Name', 'Acquisition Function Plot');
tiledlayout(3,1)

nexttile(1)
hold on;
patch([n1; flip(n1)], [LD_Surf1_m-LD_Surf1_std; flip(LD_Surf1_m+LD_Surf1_std)], 'b', 'FaceAlpha',0.25, 'EdgeColor','none')
plot(n1, LD_Surf1_m, 'b-', 'LineWidth', 2,'DisplayName','LD');
patch([n1; flip(n1)], [LCB_Surf1_m-LCB_Surf1_std; flip(LCB_Surf1_m+LCB_Surf1_std)], 'r', 'FaceAlpha',0.25, 'EdgeColor','none')
plot(n1, LCB_Surf1_m,'r-', 'LineWidth', 2,'DisplayName','LCB');
patch([n1; flip(n1)], [IVR2_Surf1_m-IVR2_Surf1_std; flip(IVR2_Surf1_m+IVR2_Surf1_std)], 'k', 'FaceAlpha',0.25, 'EdgeColor','none')
plot(n1, IVR2_Surf1_m, 'k-', 'LineWidth', 2,'DisplayName','IVR');
legend('','GD','','GV','','IVR','Location','eastoutside');
ylabel('MAE [mm]');
xlim([min(n1),max(n1)])
ylim([0 1e0])
set(gca,'XScale','log')
% set(gca,'YScale','log')
grid on
title('Surface 1, M2 and M3')

nexttile(2)
hold on;
patch([n2; flip(n2)], [LD_Surf2_m-LD_Surf2_std; flip(LD_Surf2_m+LD_Surf2_std)], 'b', 'FaceAlpha',0.25, 'EdgeColor','none')
plot(n2, LD_Surf2_m, 'b-', 'LineWidth', 2,'DisplayName','LD');
patch([n2; flip(n2)], [LCB_Surf2_m-LCB_Surf2_std; flip(LCB_Surf2_m+LCB_Surf2_std)], 'r', 'FaceAlpha',0.25, 'EdgeColor','none')
plot(n2, LCB_Surf2_m,'r-', 'LineWidth', 2,'DisplayName','LCB');
patch([n2; flip(n2)], [IVR2_Surf2_m-IVR2_Surf2_std; flip(IVR2_Surf2_m+IVR2_Surf2_std)], 'k', 'FaceAlpha',0.25, 'EdgeColor','none')
plot(n2, IVR2_Surf2_m, 'k-', 'LineWidth', 2,'DisplayName','IVR');
legend('','GD','','GV','','IVR','Location','eastoutside');
ylabel('MAE [mm]');
xlim([min(n2),max(n2)])
set(gca,'XScale','log')
set(gca,'YScale','log')
grid on
title('Surface 2, M2 and M3')

nexttile(3)
hold on;
patch([n3; flip(n3)], [LD_Surf3_m-LD_Surf3_std; flip(LD_Surf3_m+LD_Surf3_std)], 'b', 'FaceAlpha',0.25, 'EdgeColor','none')
plot(n3, LD_Surf3_m, 'b-', 'LineWidth', 2,'DisplayName','LD');
patch([n3; flip(n3)], [LCB_Surf3_m-LCB_Surf3_std; flip(LCB_Surf3_m+LCB_Surf3_std)], 'r', 'FaceAlpha',0.25, 'EdgeColor','none')
plot(n3, LCB_Surf3_m,'r-', 'LineWidth', 2,'DisplayName','LCB');
patch([n3; flip(n3)], [IVR2_Surf3_m-IVR2_Surf3_std; flip(IVR2_Surf3_m+IVR2_Surf3_std)], 'k', 'FaceAlpha',0.25, 'EdgeColor','none')
plot(n3, IVR2_Surf3_m, 'k-', 'LineWidth', 2,'DisplayName','IVR');
legend('','GD','','GV','','IVR','Location','eastoutside');
ylabel('MAE [mm]');
xlim([min(n3),max(n3)])
set(gca,'XScale','log')
set(gca,'YScale','log')
grid on
title('Surface 3, M2 and M3')

fontsize(gcf, scale=1.5)

saveas(gcf,'Paper Figures/7 Aquisition Functions/AFs.fig')
exportgraphics(gcf,'Paper Figures/7 Aquisition Functions/AFs.png')
exportgraphics(gcf,'Paper Figures/7 Aquisition Functions/AFs.eps')