%% Figure_plots.m
% Authors: Zyaire Howard and Jake Colwell
% Created: ???
% Last Major Modification: April 17, 2025
% Script to loop through all of the data generated by a study and create 
% the plots that are necessary for tuning stopping criteria, comparing models, etc.

%% Acquisition Function Figure (6 plots)
% Average over the same surface complexity (over 1a, 1b, 1c)
close all; clear; clc;

% Load data
addpath(genpath(fullfile(pwd)))
basepath = "Data/Results/20250423_SimStudy4/";
dirnames = dir(basepath+"*sim*");

LD_Surf1 = [];
LCB_Surf1 = [];
IVR2_Surf1 = [];

LD_Surf2 = [];
LCB_Surf2 = [];
IVR2_Surf2 = [];

LD_Surf3 = [];
LCB_Surf3 = [];
IVR2_Surf3 = [];

for i = 1:size(dirnames,1)
    % Load data
    dirname = basepath + "/" + dirnames(i).name;
    fname = dirname + "/" + dirnames(i).name + ".mat";
    load(fname, 'modelPerformance'); % ME is 0 over all simulation runs
    load(fname, 'nameB');
    load(fname, 'method');
    if method ~= 1
        load(fname, 'A');
    
        % Error Metrics 
        % Root Mean Squared Error
        MAE_test = table2array(modelPerformance.Test(:, 3));
        % RMSE_train = table2array(modelPerformance.Train(:, 4));
        % RMSE_CV = table2array(modelPerformance.CV(:, 4));
        if contains(nameB,'Surf1')
            n1=modelPerformance.n;
        elseif contains(nameB,'Surf2')
            n2=modelPerformance.n;
        elseif contains(nameB,'Surf3')
            n3=modelPerformance.n;
        end

        AcquisitionFunction = func2str(A);
        % Plot Calculation
        if isequal(AcquisitionFunction,'LD') && contains(nameB,'Surf1') && (method~=3)
            LD_Surf1 = cat(2, LD_Surf1, MAE_test);
        elseif isequal(AcquisitionFunction,'LD') && contains(nameB,'Surf2')
            LD_Surf2 = cat(2, LD_Surf2, MAE_test);
        elseif isequal(AcquisitionFunction,'LD') && contains(nameB,'Surf3')
            LD_Surf3 = cat(2, LD_Surf3, MAE_test);

        elseif isequal(AcquisitionFunction,'LCB_exp') && contains(nameB,'Surf1') && (method~=3)
            LCB_Surf1 = cat(2, LCB_Surf1, MAE_test);
        elseif isequal(AcquisitionFunction,'LCB_exp') && contains(nameB,'Surf2')
            LCB_Surf2 = cat(2, LCB_Surf2, MAE_test);
        elseif isequal(AcquisitionFunction,'LCB_exp') && contains(nameB,'Surf3')
            LCB_Surf3 = cat(2, LCB_Surf3, MAE_test);

        elseif isequal(AcquisitionFunction,'IVR2') && contains(nameB,'Surf1') && (method~=3)
            IVR2_Surf1 = cat(2, IVR2_Surf1, MAE_test);
        elseif isequal(AcquisitionFunction,'IVR2') && contains(nameB,'Surf2')
            IVR2_Surf2 = cat(2, IVR2_Surf2, MAE_test);
        elseif isequal(AcquisitionFunction,'IVR2') && contains(nameB,'Surf3')
            IVR2_Surf3 = cat(2, IVR2_Surf3, MAE_test);
        end
    end
end

%% Calculate Means and Std Deviations
 close all;
IVR2_Surf1_m=mean(IVR2_Surf1,2);
IVR2_Surf2_m=mean(IVR2_Surf2,2);
IVR2_Surf3_m=mean(IVR2_Surf3,2);

LCB_Surf1_m=mean(LCB_Surf1,2);
LCB_Surf2_m=mean(LCB_Surf2,2);
LCB_Surf3_m=mean(LCB_Surf3,2);

LD_Surf1_m=mean(LD_Surf1,2);
LD_Surf2_m=mean(LD_Surf2,2);
LD_Surf3_m=mean(LD_Surf3,2);

IVR2_Surf1_std=std(IVR2_Surf1,0,2);
IVR2_Surf2_std=std(IVR2_Surf2,0,2);
IVR2_Surf3_std=std(IVR2_Surf3,0,2);

LCB_Surf1_std=std(LCB_Surf1,0,2);
LCB_Surf2_std=std(LCB_Surf2,0,2);
LCB_Surf3_std=std(LCB_Surf3,0,2);

LD_Surf1_std=std(LD_Surf1,0,2);
LD_Surf2_std=std(LD_Surf2,0,2);
LD_Surf3_std=std(LD_Surf3,0,2);

% Plot all curves
figure('Units','inches','Position',[0 0 6 6]);
set(gcf, 'Name', 'Acquisition Function Plot');
t=tiledlayout(3,1,'TileSpacing','tight','Padding','tight');
ylimits = [1e-2 1e0];
xlimits = [10, 225];
nexttile(1)
hold on;
patch([n1; flip(n1)], [max(LD_Surf1_m-LD_Surf1_std,1e-10); flip(LD_Surf1_m+LD_Surf1_std)], 'b', 'FaceAlpha',0.25, 'EdgeColor','none')
plot(n1, LD_Surf1_m, 'b-', 'LineWidth', 2,'DisplayName','LD');
patch([n1; flip(n1)], [max(LCB_Surf1_m-LCB_Surf1_std,1e-10); flip(LCB_Surf1_m+LCB_Surf1_std)], 'r', 'FaceAlpha',0.25, 'EdgeColor','none')
plot(n1, LCB_Surf1_m,'r-', 'LineWidth', 2,'DisplayName','LCB');
patch([n1; flip(n1)], [max(IVR2_Surf1_m-IVR2_Surf1_std,1e-10); flip(IVR2_Surf1_m+IVR2_Surf1_std)], 'k', 'FaceAlpha',0.25, 'EdgeColor','none')
plot(n1, IVR2_Surf1_m, 'k-', 'LineWidth', 2,'DisplayName','IVR');
xticklabels([])
xticks([10 100])
xlim(xlimits)
ylim(ylimits)
set(gca,'XScale','log')
set(gca,'YScale','log')
grid on
title('Surface 1')

nexttile(2)
hold on;
patch([n2; flip(n2)], [LD_Surf2_m-LD_Surf2_std; flip(LD_Surf2_m+LD_Surf2_std)], 'b', 'FaceAlpha',0.25, 'EdgeColor','none')
plot(n2, LD_Surf2_m, 'b-', 'LineWidth', 2,'DisplayName','LD');
patch([n2; flip(n2)], [LCB_Surf2_m-LCB_Surf2_std; flip(LCB_Surf2_m+LCB_Surf2_std)], 'r', 'FaceAlpha',0.25, 'EdgeColor','none')
plot(n2, LCB_Surf2_m,'r-', 'LineWidth', 2,'DisplayName','LCB');
patch([n2; flip(n2)], [IVR2_Surf2_m-IVR2_Surf2_std; flip(IVR2_Surf2_m+IVR2_Surf2_std)], 'k', 'FaceAlpha',0.25, 'EdgeColor','none')
plot(n2, IVR2_Surf2_m, 'k-', 'LineWidth', 2,'DisplayName','IVR');
ylim(ylimits)
xlim(xlimits)
xticks([10 100])
xticklabels([])
set(gca,'XScale','log')
set(gca,'YScale','log')
legend('','GD','','GV','','IVR','Location','eastoutside');
grid on
title('Surface 2')

nexttile(3)
hold on;
patch([n3; flip(n3)], [LD_Surf3_m-LD_Surf3_std; flip(LD_Surf3_m+LD_Surf3_std)], 'b', 'FaceAlpha',0.25, 'EdgeColor','none')
plot(n3, LD_Surf3_m, 'b-', 'LineWidth', 2,'DisplayName','LD');
patch([n3; flip(n3)], [LCB_Surf3_m-LCB_Surf3_std; flip(LCB_Surf3_m+LCB_Surf3_std)], 'r', 'FaceAlpha',0.25, 'EdgeColor','none')
plot(n3, LCB_Surf3_m,'r-', 'LineWidth', 2,'DisplayName','LCB');
patch([n3; flip(n3)], [IVR2_Surf3_m-IVR2_Surf3_std; flip(IVR2_Surf3_m+IVR2_Surf3_std)], 'k', 'FaceAlpha',0.25, 'EdgeColor','none')
plot(n3, IVR2_Surf3_m, 'k-', 'LineWidth', 2,'DisplayName','IVR');
ylim(ylimits)
xlim(xlimits)
set(gca,'XScale','log')
set(gca,'YScale','log')
grid on
title('Surface 3')

ylabel(t,'Mean Absolute Error, $\mathcal L_{MAE}$ (mm)','Interpreter','latex');
xlabel(t,'Number of Points, $n$','Interpreter','latex')

fontsize(gcf, 12, "points")

saveas(gcf,'Paper Figures/7 Aquisition Functions/Figure7.fig')
exportgraphics(gcf,'Paper Figures/7 Aquisition Functions/Figure7.png')
exportgraphics(gcf,'Paper Figures/7 Aquisition Functions/Figure7.eps')