%% Figure_plots.m
% Authors: Zyaire Howard and Jake Colwell
% Created: ???
% Last Major Modification: April 17, 2025
% Script to loop through all of the data generated by a study and create 
% the plots that are necessary for tuning stopping criteria, comparing models, etc.

%% Method Comparison Figure
clc; clear; close all;

% Load data
addpath(genpath(fullfile(pwd)))
basepath = "Data/Results/20250423_SimStudy4/";
dirnames = dir(basepath+"*sim*");

figure(10);
set(gcf, 'Name', 'Method Comparison','WindowStyle', 'normal','Position',[0 0 640 420],'Color','white');
hold on
yticks([0 1 2 4 5 6 8 9 10 11])
yticklabels(["1A","1B","1C","2A","2B","2C","3A","3B","3C",''])
xticks([0 9 16 25 36 49 64 81 100 121 144 169 196 225])
%set(gca,'YGrid','on')
grid on
axis([0 225 -1 11])
title('Method Performance Comparison')
xlabel('Number of Points, n')
ylabel('Surface')

for i = 1:size(dirnames,1)
    % Load data
    dirname = basepath + dirnames(i).name;
    fname = dirname + "/" + dirnames(i).name + ".mat";
    load(fname, 'modelPerformance','n','SurfB','method');

    % Error Metrics
    ns{i}=modelPerformance.n;
    [IdealGuarantee{i}, printNumberIGs{i}] = MiniCriteria(modelPerformance,0.055);
    printNumberIG=printNumberIGs{i};
    figure(10)
    row_maj = str2double(SurfB(5));
    if SurfB(6)=='a'
        row_min=0;
    elseif SurfB(6)=='b'
        row_min=1;
    elseif SurfB(6)=='c'
        row_min=2;
    end
    row = 4*(row_maj-1)+row_min;
    if method == 1 
    scatter(printNumberIG,row,150,[0.8500 0.3250 0.0980],'filled','o','MarkerFaceAlpha',0.2)
    scatter(printNumberIG,row,150,[0.8500 0.3250 0.0980],'o','LineWidth',1)
    elseif method == 2
    scatter(printNumberIG,row,200,[0.9290 0.6940 0.1250],'filled','^','LineWidth',2,'MarkerFaceAlpha',0.2,'MarkerEdgeAlpha',1)
    scatter(printNumberIG,row,150,[0.9290 0.6940 0.1250],'^','LineWidth',1)
    elseif method == 3
    scatter(printNumberIG,row,150,[0.4940 0.1840 0.5560],'filled','square','MarkerFaceAlpha',0.2,'MarkerEdgeAlpha',1)
    scatter(printNumberIG,row,150,[0.4940 0.1840 0.5560],'square','LineWidth',1)
    end
end
legend('','Method 1','','','','','','','','','','','','','','','','','','Method 2','','','','Method 3','Location','eastoutside')
fontsize('scale',1.5)

saveas(figure(10),'Paper Figures/5 Sim Summary/ConvergenceSummary.fig')
exportgraphics(figure(10),'Paper Figures/5 Sim Summary/ConvergenceSummary.png')
exportgraphics(figure(10),'Paper Figures/5 Sim Summary/ConvergenceSummary.eps')